### ISSUE TITLE
Is there any install guide for vops?

### ISSUE THREAD

**Issue by ctyytc** [postgrespro/vops#20]
Is there any install guide for vops?

**Comment by knizhnik** [comment]
VOPS is standard Postgres extension: there are no differences in building andinstallation of VOPS comparing with most of other Postgres extension.
And procedure of building Postgres extension is explained in many places, including Postgres documentation.

The only small specific of VOPS is that you may want to include in shared_preload_libraries (although it is not required) to force registration of  VOPS post analyze hook (otherwise it will be registered lazily only on first explicit VOPS function invocation).

**Comment by ctyytc** [comment]
@knizhnik Thanks for your answer😁
